apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd3
  name: etcd3
  namespace: default
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    app: etcd3
  sessionAffinity: None
  type: ClusterIP
